- name: Install node
  become: true
  apt:
    name: ['nodejs', 'npm']
  tags:
    - install
    - node

- name: Ensure physical dir for nvm
  file:
    dest: "{{ lookup('env', 'HOME') }}/.nvm"
    mode: 0755
    state: directory
  tags:
    - install
    - node

- name: Install node version manager
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
  tags:
    - install
    - node

- name: Install Deno
  shell: >
    curl -fsSL https://deno.land/x/install/install.sh | sh
  tags:
    - install
    - node
