- name: Install tmux
  become: true
  apt: name=tmux
  tags:
    - install
    - tmux

- name: Install Tmux Plugin Manager
  shell: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  tags:
    - install
    - tmux
