- name: core | Install System Packages 1
  become: true
  ansible.builtin.apt:
    name: [
      "build-essential",
      "cmake",
      "gnutls-bin",
      "pkg-config",
      "libpthread-stubs0-dev",
      "locales",
      "xz-utils",
      "apt-transport-https"
    ]
  tags:
    - install
    - core

- name: core | Install System Packages 2
  become: true
  ansible.builtin.apt:
    name: [
      "unzip",
      "libtool",
      "libtool-bin",
      "gettext",
      "tree",
      "ca-certificates"
    ]
  tags:
    - install
    - core

- name: core | Install System Packages 3
  become: true
  ansible.builtin.apt:
    name: [
      "curl",
      "gnupg",
      "htop",
      "lsof",
      "python3-pip",
      "pavucontrol",
      "moreutils",
      "gnupg2",
      "zip",
      "lib32ncurses6",
      "lib32stdc++6",
      "libdb-dev",
      "libgdbm-dev",
      "libffi-dev",
      "libgmp-dev",
      "libncurses5-dev",
      "libreadline6-dev",
      "libssl-dev",
      "libyaml-dev",
      "snapd",
      "uuid-dev",
      "wget",
      "wslu"
    ]
  tags:
    - install
    - core
