---
- name: dotfiles | Installing GNU stow
  become: true
  ansible.builtin.apt:
    name: stow
  tags:
    - install
    - dotfiles
    - stow

- name: dotfiles | Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:code-chimp/dotfiles.stow.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: true
    update: true
    accept_hostkey: true
    version: main
  tags:
    - install
    - dotfiles
    - stow

- name: dotfiles | Stow dotfiles
  ansible.builtin.shell: cd $HOME/.dotfiles && ./debian
  tags:
    - install
    - dotfiles
    - stow
