---
- name: fonts | Ensure a Fonts Directory
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/.fonts"
    mode: "0755"
    state: directory
  tags:
    - install
    - fonts

- name: fonts | Make a Temp Font Directory
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/.fonttemp"
    mode: "0755"
    state: directory
  tags:
    - install
    - fonts

- name: fonts | Download Fira Code Patched
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
    dest: "{{ lookup('env', 'HOME') }}/.fonttemp/FiraCode.zip"
  tags:
    - install
    - fonts

- name: fonts | Download UbuntuMono Patched
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/UbuntuMono.zip
    dest: "{{ lookup('env', 'HOME') }}/.fonttemp/UbuntuMono.zip"
  tags:
    - install
    - fonts

- name: fonts | Install Nerd Fonts
  ansible.builtin.shell: >
    cd $HOME/.fonttemp
    && unzip FiraCode.zip
    && unzip UbuntuMono.zip
    && mv *.ttf $HOME/.fonts
    && cd ..
    && rm -rf .fonttemp
  tags:
    - install
    - fonts

- name: fonts | Install Favorite Font Packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: [
      "fonts-powerline",
      "fonts-firacode",
      "fonts-noto-color-emoji",
      "fonts-emojione"
    ]
  tags:
    - install
    - productivity
