- name: Add GitHub CLI repository
  become: true
  shell: >
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/etc/apt/trusted.gpg.d/github-cli.gpg
    && chmod go+r /etc/apt/trusted.gpg.d/github-cli.gpg
    && echo "deb [arch="$(dpkg --print-architecture)"] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
  tags:
    - install
    - gh

- name: Install GitHub CLI
  become: true
  apt:
    update_cache: true
    name: "gh"
  tags:
    - install
    - gh
