---
- name: golang | Go archive download
  become: true
  ansible.builtin.get_url:
    url: https://golang.org/dl/go{{ go_ver }}.linux-amd64.tar.gz
    dest: /tmp/go{{ go_ver }}.linux-amd64.tar.gz
  tags:
    - install
    - golang

- name: golang | Install Go
  become: true
  ansible.builtin.shell: >
    rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/go{{ go_ver }}.linux-amd64.tar.gz
    && rm /tmp/go{{ go_ver }}.linux-amd64.tar.gz
  tags:
    - install
    - golang
