---
- name: java | Install OpenJDK LTS
  become: true
  ansible.builtin.apt:
    name: [
      "openjdk-{{ jdk_lts }}-jdk",
      "openjdk-{{ jdk_lts }}-jdk-headless",
      "openjdk-{{ jdk_lts }}-jre",
      "openjdk-{{ jdk_lts }}-jre-headless"
    ]
  tags:
    - install
    - java
