- name: LibreOffice PPA (ppa:libreoffice/ppa)
  become: true
  shell: apt-add-repository -y ppa:libreoffice/ppa
  tags:
    - install
    - libreoffice

- name: Install LibreOffice
  become: true
  apt:
    name: libreoffice
    state: latest
  tags:
    - install
    - libreoffice
