---
- name: libreoffice | LibreOffice PPA (ppa:libreoffice/ppa)
  become: true
  ansible.builtin.shell: apt-add-repository -y ppa:libreoffice/ppa
  tags:
    - install
    - libreoffice

- name: libreoffice | Install LibreOffice
  become: true
  ansible.builtin.apt:
    name: libreoffice
    state: latest
  tags:
    - install
    - libreoffice
