---
- name: microsoft | Download .NET .deb
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/config/ubuntu/{{ buntu_ver }}/packages-microsoft-prod.deb
    dest: /tmp/microsoft.deb
  tags:
    - install
    - dotnet

- name: microsoft | Install .NET .deb package
  become: true
  ansible.builtin.apt:
    deb: /tmp/microsoft.deb
  tags:
    - install
    - dotnet

- name: microsoft | Install Microsoft Packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: [
      "dotnet-sdk-8.0",
      "powershell"
    ]
  tags:
    - install
    - dotnet

- name: microsoft | Install .NET tools
  ansible.builtin.shell: >
    dotnet tool install -g dotnet-ef
    && dotnet tool install -g dotnet-aspnet-codegenerator
  tags:
    - install
    - dotnet
