- name: node | Install node
  become: true
  ansible.builtin.apt:
    name: ['nodejs', 'npm']
  tags:
    - install
    - node

- name: node | Reconfigure locales for NPM
  become: true
  ansible.builtin.shell: >
    update-locale "en_US.UTF-8"
    && locale-gen --purge "en_US.UTF-8"
    && dpkg-reconfigure --frontend noninteractive locales
  tags:
    - install
    - node

- name: node | Get volta
  ansible.builtin.get_url:
    url: https://get.volta.sh
    dest: /tmp/volta.sh
  tags:
    - install
    - volta
    - node

- name: node | Install Volta
  ansible.builtin.script: /tmp/volta.sh
  tags:
    - install
    - volta
    - node

- name: node | Enable Volta pnpm support
  ansible.builtin.shell: >
    echo "export VOLTA_FEATURE_PNPM=1" >> $HOME/.zshrc
  tags:
    - install
    - volta
    - node

- name: node | Install default Node environment
  args:
    executable: /usr/bin/zsh
  ansible.builtin.shell: >
    source $HOME/.zshrc
    && volta install node@{{ node_edge }} yarn@3 pnpm
    && npm i -g @mermaid-js/mermaid-cli firebase-tools npm-check-updates prettier serverless typescript
  tags:
    - install
    - volta
    - node

- name: node | Get Deno
  ansible.builtin.get_url:
    url: https://deno.land/x/install/install.sh
    dest: /tmp/deno.sh
  tags:
    - install
    - node
    - deno

- name: node | Install Deno
  ansible.builtin.script: /tmp/deno.sh
  tags:
    - install
    - node
    - deno
