- name: Install node
  become: true
  apt:
    name: ['nodejs', 'npm']
  tags:
    - install
    - node

- name: Reconfigure locales for NPM
  become: true
  shell: >
    update-locale "en_US.UTF-8"
    && locale-gen --purge "en_US.UTF-8"
    && dpkg-reconfigure --frontend noninteractive locales
  tags:
    - install
    - node

- name: Install Volta
  shell: >
    curl https://get.volta.sh | bash
  tags:
    - install
    - volta
    - node

- name: Enable Volta pnpm support
  shell: >
    echo "export VOLTA_FEATURE_PNPM=1" >> ~/.zshrc
  tags:
    - install
    - volta
    - node


- name: Install default Node environment
  args:
    executable: /usr/bin/zsh
  shell: >
    source $HOME/.zshrc
    && volta install node@{{ node_edge }} yarn@3 pnpm
  tags:
    - install
    - volta
    - node

- name: Install Deno
  shell: >
    curl -fsSL https://deno.land/x/install/install.sh | sh
  tags:
    - install
    - node
