---
- name: nvim | Neovim PPA (ppa:neovim-ppa/unstable)
  become: true
  ansible.builtin.shell: apt-add-repository -y ppa:neovim-ppa/unstable
  tags:
    - install
    - neovim

- name: nvim | Install Neovim
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: neovim
    state: latest
  tags:
    - install
    - neovim

- name: nvim | Cloning NeoVim config
  ansible.builtin.git:
    repo: 'git@github.com:code-chimp/nvim.config.git'
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    recursive: true
    update: true
    accept_hostkey: true
    version: main
  tags:
    - install
    - neovim
