- name: GIMP PPA (ppa:ubuntuhandbook1/gimp)
  become: true
  apt_repository:
   repo: ppa:ubuntuhandbook1/gimp
   state: present
   update_cache: True
  tags:
    - install
    - productivity

- name: Gimp Fix Keyring
  become: true
  shell: >
    apt-key export 852541CB | gpg --dearmor -o /etc/apt/trusted.gpg.d/gimp.gpg
    && apt-key --keyring /etc/apt/trusted.gpg del 852541CB
  tags:
    - install
    - productivity

- name: Inkscape PPA (ppa:inkscape.dev/stable)
  become: true
  apt_repository:
   repo: ppa:inkscape.dev/stable
   state: present
   update_cache: True
  tags:
    - install
    - productivity

- name: Inkscape Fix Keyring
  become: true
  shell: >
    apt-key export B9A06DE3 | gpg --dearmor -o /etc/apt/trusted.gpg.d/inkscape.gpg
    && apt-key --keyring /etc/apt/trusted.gpg del B9A06DE3
  tags:
    - install
    - productivity

- name: Install Random Productivity Tools
  become: true
  apt:
    update_cache: yes
    name: [
      "bc",
      "wireshark",
      "fzf",
      "xclip",
      "tldr",
      "ripgrep",
      "gimp",
      "gimp-data",
      "gimp-data-extras",
      "gimp-gmic",
      "gimp-gutenprint",
      "inkscape",
      "keepassxc"
    ]
  tags:
    - install
    - productivity
