- name: productivity | GIMP PPA (ppa:ubuntuhandbook1/gimp)
  become: true
  ansible.builtin.shell: apt-add-repository -y ppa:ubuntuhandbook1/gimp
  tags:
    - install
    - productivity

- name: productivity | Inkscape PPA (ppa:inkscape.dev/stable)
  become: true
  ansible.builtin.shell: apt-add-repository -y ppa:inkscape.dev/stable
  tags:
    - install
    - productivity

- name: productivity | KeepassXC PPA (ppa:phoerious/keepassxc)
  become: true
  ansible.builtin.shell: apt-add-repository -y ppa:phoerious/keepassxc
  tags:
    - install
    - productivity

- name: productivity | Install Random Productivity Tools
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: [
      "bc",
      "wireshark",
      "fzf",
      "xclip",
      "tldr",
      "ripgrep",
      "gimp",
      "gimp-data",
      "gimp-data-extras",
      "gimp-gmic",
      "gimp-gutenprint",
      "inkscape",
      "keepassxc"
    ]
  tags:
    - install
    - productivity
