---
- name: ruby | Installing rbenv
  ansible.builtin.git:
    repo: 'https://github.com/rbenv/rbenv.git'
    dest: "{{ lookup('env', 'HOME') }}/.rbenv"
  tags:
    - install
    - ruby

- name: ruby | Installing ruby build
  ansible.builtin.git:
    repo: 'https://github.com/rbenv/ruby-build.git'
    dest: "{{ lookup('env', 'HOME') }}/.rbenv/plugins/ruby-build"
  tags:
    - install
    - ruby

- name: ruby | Enable rbenv
  ansible.builtin.shell: >
    echo 'eval "$(~/.rbenv/bin/rbenv init - zsh)"' >> $HOME/.zshrc
  tags:
    - install
