---
- name: ssh | Ensure bitbucket .ssh directory exists.
  ansible.builtin.file:
    dest: "{{ bb_dest_key | dirname }}"
    mode: "0700"
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: ssh | Install config file
  ansible.builtin.copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: "0644"
  tags:
    - dotfiles
    - install
    - ssh

- name: ssh | Install bitbucket ssh key
  ansible.builtin.copy:
    src: "{{ bb_source_key }}"
    dest: "{{ bb_dest_key }}"
    mode: "0600"
  tags:
    - dotfiles
    - install
    - ssh

- name: ssh | Install bitbucket ssh key public
  ansible.builtin.copy:
    src: "{{ bb_source_key }}.pub"
    dest: "{{ bb_dest_key }}.pub"
    mode: "0644"
  tags:
    - dotfiles
    - install
    - ssh

- name: ssh | Ensure github .ssh directory exists.
  ansible.builtin.file:
    dest: "{{ gh_dest_key | dirname }}"
    mode: "0700"
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: ssh | Install github ssh key
  ansible.builtin.copy:
    src: "{{ gh_source_key }}"
    dest: "{{ gh_dest_key }}"
    mode: "0600"
  tags:
    - dotfiles
    - install
    - ssh

- name: ssh | Install github ssh key public
  ansible.builtin.copy:
    src: "{{ gh_source_key }}.pub"
    dest: "{{ gh_dest_key }}.pub"
    mode: "0644"
  tags:
    - dotfiles
    - install
    - ssh
