- name: statics | Copy WSL2 config
  become: true
  ansible.builtin.copy:
    src: "./static/wsl.conf"
    dest: "/etc/wsl.conf"
    mode: "0644"
  tags:
    - install
    - post

- name: statics | Copy Post Install script
  ansible.builtin.copy:
    src: "./static/post.sh"
    dest: "{{ lookup('env', 'HOME') }}"
    mode: "0777"
  tags:
    - install
    - post

- name: statics | Copy Post Install Instructions
  ansible.builtin.copy:
    src: "./static/POST_INSTALL.md"
    dest: "{{ lookup('env', 'HOME') }}"
    mode: "0666"
  tags:
    - install
    - post
