---
- name: vim | Install vim and gvim
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: [
      "vim",
      "vim-common",
      "vim-gtk3",
      "vim-gui-common",
      "vim-runtime",
      "vim-tiny"
    ]
  tags:
    - install
    - dotfiles
    - vim

- name: vim | Ensure a plugin directory
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/.vim/autoload/"
    mode: "0755"
    state: directory
  tags:
    - install
    - dotfiles
    - vim

- name: vim | Install Vim-Plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ lookup('env', 'HOME') }}/.vim/autoload/plug.vim"
  tags:
    - install
    - dotfiles
    - vim
