---
- name: zsh | Install zsh
  become: true
  ansible.builtin.apt:
    name: zsh
    state: latest
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: zsh | Change Default Shell
  become: true
  ansible.builtin.shell: chsh -s `which zsh` tgoshinski
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: zsh | Create empty zsh config
  ansible.builtin.shell: echo '# replace me' >> $HOME/.zshrc
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: zsh | Get ohmyzsh
  ansible.builtin.get_url:
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-installer"
    mode: "0755"
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: zsh | Install ohmyzsh
  ansible.builtin.shell: >
    $HOME/.oh-my-installer
    && rm $HOME/.oh-my-installer
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: zsh | Clone Dracula Theme for zsh
  ansible.builtin.git:
    repo: 'https://github.com/dracula/zsh.git'
    dest: "{{ lookup('env', 'HOME') }}/dracula-zsh"
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: zsh | Symlink Dracula Theme to .oh-my-zsh
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/dracula-zsh/dracula.zsh-theme"
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/themes/dracula.zsh-theme"
    state: link
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

## plugin example
# - name: zsh | Install zsh Plugin autosuggestions
#   ansible.builtin.git:
#     repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
#     dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
#   tags:
#     - install
#     - productivity
#     - dotfiles
#     - zsh
