# Install and set up all of my default Ubuntu packages

- hosts: localhost
  vars:
    primaryuser: "tgoshinski"
    buntuver: "22.04"
    buntuname: "jammy"
    gover: "1.20.4"
    source_key: "./.ssh/config"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/config"
    bb_source_key: "./.ssh/bitbucket/id_rsa"
    bb_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/bitbucket/id_rsa"
    gh_source_key: "./.ssh/github/id_rsa"
    gh_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/github/id_rsa"
  pre_tasks:
  - name: Update Package Manager
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/github-cli.yml
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/golang.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/vim.yml
    - import_tasks: tasks/nvim.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/rust.yml
    - import_tasks: tasks/ruby.yml
    - import_tasks: tasks/java.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/microsoft.yml
    - import_tasks: tasks/libreoffice.yml
    - import_tasks: tasks/productivity.yml
    - import_tasks: tasks/statics.yml
